### ISSUE TITLE
Cells not realoading code in development

### ISSUE THREAD

**Issue by Startouf** [trailblazer/cells-rails#10]
In my development environment my code is no longer reloading automatically. It seems to match my upgrade to cells-rails 0.0.6 and the latest cells. The rest of my app (controllers, Rails views) seems to reload correctly. How can I check the current configuration for cells caching ? 

So right now I need to restart the server even if the cell crashes because of a syntax error :'(...

I will try to dig and blame the commit that introduced that...

**Comment by apotonick** [comment]
Check if this is run: https://github.com/trailblazer/cells-rails/blob/master/lib/cell/railtie.rb#L67

**Comment by Startouf** [comment]
Hey, I added a byebug in the `Rails.env == 'development'` branch but never got any break in my console...
(I had made an initializer where I patched cells code with the content of the file you linked)

Any idea where the problem might be ?

cells (4.1.3)
cells-erb (0.0.9)
cells-rails (0.0.6)
kaminari-cells (0.0.4)
trailblazer-cells (0.0.3)

**Comment by apotonick** [comment]
Maybe @timoschilling got an idea?

**Comment by Startouf** [comment]
When I roll back, up to cells 4.1.1 it still works. The bug was introduced with cells 4.1.2. My version of cells-rails stayed the same, so I guess the bug lies in cells and not cells-rails. SHould the issue be moved to the main repo ?

**Comment by apotonick** [comment]
It must be fixed here as Cells shouldn't contain any Rails code. What did we remove in 4.1.2?

**Comment by contentfree** [comment]
This still exists with cells-rails 0.0.7 and cells 4.1.6. 

If a cell has a syntax error then reloading seems to work until the file is successfully parsed at which point I have to restart the server to get new changes.

**Comment by apotonick** [comment]
View or cell class? :thinking:

**Comment by apotonick** [comment]
I don't have time to work on this in the next weeks, it's up to the community to fix it, so give it a go. :wink:

**Comment by contentfree** [comment]
It's the view (`concepts/thing/views/show.haml`). If there's an error it
will reload until the error is gone and from then on it requires a server
restart to reload the view.

I assume it could be fixed by changing/adding something in the railtie.

**Comment by tbuehlmann** [comment]
@Startouf, @contentfree: Can you provide an example application including a Gemfile.lock?

**Comment by Startouf** [comment]
I'm not working on many cells views anymore since we've developed our new frontend application, and I see in my Gemfile.lock my cells version number is now (4.1.7) and I don't recall having those problems again... maybe @contentfree still has some repro steps ?
